apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-task-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: os-task-one #image name(local development)
        image: gorret/os-task-one:v1 #image name from docker hub
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: os-task-one-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 5000
  type: NodePort  #  
